### ISSUE TITLE
官网首页的例子怎么实现的

### ISSUE THREAD

**Issue by yoyoping** [sbfkcel/fast-astar#2]
官网首页的例子怎么实现的，有demo代码吗?

**Comment by sbfkcel** [comment]
gh-pages 分支

https://github.com/sbfkcel/fast-astar/tree/gh-pages

**Comment by yoyoping** [comment]
> gh-pages分支
> 
> https://github.com/sbfkcel/fast-astar/tree/gh-pages

好的，谢谢
