### ISSUE TITLE
内存溢出

### ISSUE THREAD

**Issue by msdog** [sbfkcel/fast-astar#3]
这个数量的情况没有问题
![image](https://user-images.githubusercontent.com/34001318/132827146-e1e54b2b-6b3a-4434-8621-04e652984bf1.png)
但是下面这个情况就内存溢出了
![image](https://user-images.githubusercontent.com/34001318/132827257-83ea0bdc-0e84-4e04-9060-2139271d2fc6.png)
![image](https://user-images.githubusercontent.com/34001318/132827361-0fcb821c-ba26-43e3-b831-cfa2b5efafcb.png)
![image](https://user-images.githubusercontent.com/34001318/132827509-4a16d322-2aba-44d0-b159-a15d02714ffa.png)

地图有点大
![image](https://user-images.githubusercontent.com/34001318/132827418-bc371b2d-1abe-4986-9630-48702a30db36.png)

**Comment by sbfkcel** [comment]
能丢个完整的DEMO吗？

**Comment by sbfkcel** [comment]
![image](https://user-images.githubusercontent.com/5469785/132877989-2f74e2ac-d514-41d3-bc33-17ccb8cd1c83.png)
我简单模拟了下，没有异常

**Comment by msdog** [comment]
http://jsrun.net/7fTKp/edit

**Comment by sbfkcel** [comment]
更到最新的看看。

**Comment by msdog** [comment]
我用了一下感觉性能上还有进步的空间, 我改用javascript-star了 这个速度很快

**Comment by sbfkcel** [comment]
> 我用了一下感觉性能上还有进步的空间, 我改用javascript-star了 这个速度很快

这个库，你的例子要多少时间？

**Comment by msdog** [comment]
![image](https://user-images.githubusercontent.com/34001318/133015682-ab891448-9811-42f0-880d-ceb49c9426ff.png)

**Comment by msdog** [comment]
![image](https://user-images.githubusercontent.com/34001318/133015711-dc74bac1-b584-4a9f-a540-830bc92a24c4.png)

**Comment by msdog** [comment]
[test.zip](https://github.com/sbfkcel/fast-astar/files/7151040/test.zip)

**Comment by msdog** [comment]
![image](https://user-images.githubusercontent.com/34001318/133017273-5cc17954-51b9-4dd4-8653-a7fd031a07e5.png)
这个是javascript-star

**Comment by sbfkcel** [comment]
验证下其搜索的结果是否一至呢？

**Comment by msdog** [comment]
其他结果最低都要500ms

**Comment by msdog** [comment]
然而JavaScript-astar 一般30ms左右

**Comment by sbfkcel** [comment]
我稍微测试了下，两者获取的结果不太一至。需要具体再验证一下

**Comment by sbfkcel** [comment]
再更新试试
